#!/usr/bin/env bash
# a script that fixes network routing by changing to default port 80 and restart nginx

sudo sed -i "s/8080 default_server;/80 default_server;/" /etc/nginx/sites-enabled/default
sudo service nginx restart
