#!/usr/bin/env bash
# a script that fixes network routing by changing to default port 80 and restart nginx
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
