#!/usr/bin/env bash
# Displays "Best School" 10 times using a for loop.

n=1

while [ $n -lt 21 ]
do
  echo "$n"
  case $n in
    4)
      echo "bad luck from China";;
    9)
      echo "bad luck from Japan";;
    17)
      echo "bad luck from Italy";;
  esac
  ((n++))
done
