#!/usr/bin/env bash
# Displays "Best School" 10 times using a for loop.

min=0
hr=0

while [ $hr -lt 13 ]
do
  ((min = min % 60))
  if [ $min -eq 0 ]
  then
    echo "Hour: $hr"
    ((hr++))
  else
    echo "$min"
  fi
  ((min++))
done
